name: hackathon_frontend
version: 1.0.0+1
description: Hackathon-ready Flutter app
publish_to: "none"
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  provider: ^6.1.1
  fl_chart: ^0.65.0
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
